### ISSUE TITLE
No podspec found for `manual_camera` in `.symlinks/plugins/manual_camera/ios`

### ISSUE THREAD

**Issue by e1engineer** [Afonsocraposo/manual_camera#2]
Attempting to use this package, and receive the following error on iOS when trying to run:

No podspec found for `manual_camera` in `.symlinks/plugins/manual_camera/ios`

Thanks in advance for the help!

**Comment by afonsocraposo** [comment]
Hello. I still have not implemented the iOS part of this plugin. I don't have much experience on iOS, but I'd like to try to implement that as well. Unfortunately, I can only do that after the 14th of January

**Comment by ciento** [comment]
You should be able to solve this by doing these two steps: 

1. edit the file `/ios/camera.podspec` in line 5: `s.name = 'camera'` -> `s.name = 'manual_camera'` 
2. rename the file from `camera.podspec` to `manual_camera.podspec`

With these changes I was able to build and run on iOS.

**Comment by afonsocraposo** [comment]
I'll apply your fix and push it to the repo. Thank you @ciento

**Comment by afonsocraposo** [comment]
Fixed in https://github.com/Afonsocraposo/manual_camera/commit/05d45ed854b914d38c38d4c9cc578284df132c7e using @ciento's solution.
