### ISSUE TITLE
focusDistance and other with no effect

### ISSUE THREAD

**Issue by 457r0n4u7** [Afonsocraposo/manual_camera#4]
Hi Afonso,

Nice work although outdated! I am testing in legacy mode and realized no matter what I set as `shutterSpeed` or `focusDistance` the camera image looks the same focus very far away and exposure does not change (Android). I am mainly interested in (very) long exposures.

What were your settings/versions of all libraries that used to work?

**Comment by afonsocraposo** [comment]
Hello @457r0n4u7 ,

Thank you for your comment. I'm sorry to know that.
I created this package for my Master thesis and it worked well at the time. I don't know the settings/versions of all libraries that used to work, but maybe I can point you to a different package that appears to offer exposure control: [camerawesome](https://pub.dev/packages/camerawesome).

I'm sorry that I can't be more of help. Good luck with your project!
